fix: Homebrew/workbrew instantiation fix of error
$ brew outdated
Error: conflicting Homebrew wrapper configuration!
HOMEBREW_FORCE_BREW_WRAPPER was set to /opt/workbrew/bin/brew
but brew was invoked by /opt/homebrew/Cellar/bash/5.3.9/bin/bash.